post/urls.py
from .views import *
from django.urls import path, URLPattern
from django.conf import settings
from django.conf.urls.static import static

app_name = 'post'
urlpatterns = [
    path("postlist/",postlist,name="postlist"),
    path("uploadFile/",uploadFile,name="uploadFile"),
    path("saveFile/",saveFile,name="saveFile"),
    path("file/",file,name="file"),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

recycleledger_audit_web/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',mainpage, name="mainpage"),
    path("post/",include("post.urls"))

]

post/models.py
from django.db import models


class Document(models.Model):
    title = models.CharField(max_length=200)
    uploadedFile = models.FileField(upload_to="result/")
    dateTimeOfUpload = models.DateTimeField(auto_now=True)

# views.py에 작성했던 Report 모델 예시

class Report(models.Model):
    date = models.CharField(max_length=200,null=True)
    PO_name = models.CharField(max_length=200,null=True)
    address = models.CharField(max_length=200,null=True) 
    collector = models.CharField(max_length=200,null=True) 
    quantity = models.IntegerField(null=True) 
    converted_qty = models.FloatField(null=True) 
    collecting_company = models.CharField(max_length=200,null=True)

post/views.py
from django.shortcuts import render, redirect
from .models import *
from openpyxl import Workbook # 엑셀을 만드는 api (엑셀 미설치 시에도 동작)
from io import BytesIO # 엑셀 파일을 전송 할 수 있도록 바이트 배열로 변환
from django.core.files.storage import FileSystemStorage
import pandas as pd
from datetime import datetime
from django.conf import settings
# Create your views here.

def postlist(request):
    documents = Document.objects.all()
    excel=Report.objects.all()
    return render(request, "post/postlist.html", context={
        "files": documents,
        "datas":excel
    })

def uploadFile(request):
    return render(request,"post/upload-file.html")

def saveFile(request):
    if request.method == "POST":
        # Fetching the form data
        fileTitle = request.POST["fileTitle"]
        uploadedFile = request.FILES["uploadedFile"]

        # Saving the information in the database
        document = Document(
            title=fileTitle,
            uploadedFile=uploadedFile
        )
        document.save()
    return redirect('post:postlist')
   
def file(request):
    if request.method == "POST":
        fileTitle = request.POST["fileTitle"]
        uploadedFile = request.FILES["uploadedFile"]
        
        # n_path=settings.MEDIA_ROOT+'/'+datetime.today().strftime("%Y-%m-%d")
        
        fs=FileSystemStorage()
        
        filename=fs.save(uploadedFile.name,uploadedFile)
        url=fs.url(filename)
        
        print(filename)
        print(url)

        exceldata=pd.read_excel("."+url)

        for idx, i in exceldata.iterrows():
            
            document = Report(
            date =i['Date of Collection'],
            PO_name =i['PO name'],
            address=i['Region(Address)'],
            collector=i['Collector'],
            quantity =i['Quantity(can)'],
            converted_qty = i['Converted qty(kg)'],
            collecting_company=i['Collecting company'],
            )      
            document.save()
        
    return redirect('post:postlist')

# 내가 짜다가 만 report view - 멘토님이 보내주신 엑셀 파일 기반으로 대충 해봄
# 중간의 Report는 model에 생성할 db에 들어갈것 
""" 
def report(request):
    wb = Workbook()  # 엑셀 생성
    ws = wb.active	# 엑셀 활성화
    excelfile = BytesIO() #바이트 배열 생성

    ws['A1']= 'date' # 엑셀 a1 열 이름 정하기
    ws['B1']= 'PO_name'
    ws['C1']= 'address'
    ws['D1']= 'collector'
    ws['E1']= 'quantity'
    ws['F1']= 'converted_qty'
    ws['G1']= 'conllecting_company'


    for i in text: # text 는 db 에 저장된 내용 전체
        content=[i.company,i.product_name,i.count]   #리스트 형태로 1 행씩 생성(a1, b1, c1) 에 각각
        ws.append(content) # 엑셀에 1행을 추가

    wb.close()  #엑셀 닫기
    wb.save(excelfile) # 바이트배열로 저장 (mail 전송 하려면 바이트형태로 변환 되어야 함)

    # 엑셀을 input tag 로 입력받아 db에 저장 하는 코드
    request.FILES['files'].save_to_database(
        model = Report, 	#매핑 대상 db
        mapdict= ['date', 'PO_name', 'address', 'collector', 'quantity', 'converted_qty', 'conllecting_company'  ]) # 칼럼에 매핑하기
"""

recycleledger_audit_web/views.py
from django.shortcuts import render


def mainpage(request):
    return render(request, 'main/mainpage.html')

post/templates/post/postlist.html
<!DOCTYPE html>
<html lang="en">
<body>
    <table>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>File Path</th>
            <th>Upload Date & Time</th>
        </tr>
        {% for file in files %}
            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.title }}</td>
                <td>{{ file.uploadedFile.url }}</td>
                <td>{{ file.dateTimeOfUpload }}</td>
            </tr>
        {% endfor %}

    </table>
    <table>
        <tr>
            <th>date</th>
            <th>PO_name</th>
            <th>address</th>
            <th>collector</th>
            <th>quantity</th>
            <th>converted_qty</th>
            <th>conllecting_company</th>
        </tr>
        <br>
        {% for data in datas %}
              
            <tr>
                <td>{{ data.date }}</td>
                <td>{{ data.PO_name }}</td>
                <td>{{ data.address }}</td>
                <td>{{ data.collector }}</td>
                <td>{{ data.quantity }}</td>
                <td>{{ data.converted_qty }}</td>
                <td>{{ data.conllecting_company }}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

post/templates/post/upload-file.html
<!DOCTYPE html>
<html lang="kr">
    <form action="{% url 'post:file' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="fileTitle" placeholder="Enter a title">
        <input type="file" name="uploadedFile">
        <input type="submit" value="Upload">
    </form>

 


</html>

recycleledger_audit_web/templates/main/mainpage.html
<!DOCTYPE html>
<html lang="en">

<head> excel </head>

<body>
    <h2>
        <a href="{% url 'post:uploadFile' %}">
            엑셀넣기
        </a>
        
    </h2>


</body>